name: rd-winrm-plugin
version: 0.6.0
rundeckPluginVersion: 1.0
author: Volodymyr Babchynskyy
date: 01.09.2015
providers:
  - name: WinRMexe
    title: WinRM PS Executor
    description: Executing PowerShell Scripts or commands on remote windows computer
    service: NodeExecutor
    plugin-type: script
#    script-interpreter: []
    script-file: winrmexe.rb
#    script-args: ${config.realm} ${config.username} ${config.password} ${node.hostname} ${exec.command}
    interpreter-args-quoted: true
    config:
      - name: krb5_realm
        title: Kerberos Realm
        type: String
        required: false
        description: "Kerberos Realm FQDN in capital letters"
        scope: Instance
        renderingOptions:
          instance-scope-node-attribute: "krb5_realm"
      - name: user
        title: Username
        description: "Username in DOMAIN/name form"
        type: String
        required: false
        scope: Instance 
        renderingOptions:
          instance-scope-node-attribute: "user"
      - name: pass
        title: Password
        description: "Password"
        type: String
        required: false
        scope: Instance
        renderingOptions:
          displayType: PASSWORD
      - name: authtype
        title: Auth type
        description: "Autentification type"
        type: Select
        values: "kerberos, plaintext, ssl"
        default: "plaintext"
        required: true
        scope: Instance
        renderingOptions:
          instance-scope-node-attribute: "authtype"

  - name: WinRMcp
    title: WinRM File Copier
    service: FileCopier
    plugin-type: script
#    script-interpreter: [interpreter]
    script-file: winrmcp.rb
    script-args: ${node.hostname} ${file-copy.file} ${file-copy.destination}
    config:
      - name: krb5_realm
        title: Kerberos Realm
        type: String
        required: false
        description: "Kerberos Realm FQDN in capital letters"
        scope: Instance
        renderingOptions:
          instance-scope-node-attribute: "krb5_realm"
      - name: user
        title: Username
        type: String
        required: true
        description: "Username in DOMAIN/name form"
        scope: Instance 
        renderingOptions:
          instance-scope-node-attribute: "user"
      - name: pass
        title: Password
        type: String
        required: true
        description: "Password"
        scope: Instance
        renderingOptions:
          displayType: PASSWORD
      - name: authtype
        title: Auth type
        description: "Autentification type"
        type: Select
        values: "kerberos, plaintext, ssl"
        default: "plaintext"
        required: true
        scope: Instance
        renderingOptions:
          instance-scope-node-attribute: "authtype"

